language: generic 

sudo: required

services:
        - docker

before_install:
        - docker build -t eden1515/docker-react -f Dockerfile.dev .
          
script:
        - docker run -e CI=true eden1515/docker-react npm run test



